### ISSUE TITLE
Delete Cache

### ISSUE THREAD

**Issue by fritzdacat** [lochmueller/fl_realurl_image#14] opened 2016-12-05 16:20 UTC
How can you delete the cache of the pictures when a picture has changed?

**Comment by lochmueller** [comment] 2016-12-05 16:41
There is no "delete" mechanism, because the image cache is also not deletable (only in install tool). A clenup process would be a great feature...

**Comment by fritzdacat** [comment] 2016-12-05 16:44
But in the version for TYPO3 4.5 the image was changed when a new one came.
What should I do if I want to change my pictures?

If I clear the image cache in the installtool. Do the pictures then get new filenames?

**Comment by lochmueller** [comment] 2016-12-05 16:52
The picture get a new name, if a new temp image is generated. This is the only time. I thought about a migration to the caching framework to handle expire times and clear cache functions more easily... But I think this is a task for 2017 ;)

**Comment by fritzdacat** [comment] 2016-12-05 17:41
Ok, if I have pictures that are not entered via TYPO3, but have a nice name via imageRealUrl, where will they store this information?

I must necessarily find a possibility that when I import the images again, I can delete the cache of the relevant pictures.

I already live with the page and use the extension. But the problem was now noticed

**Comment by fritzdacat** [comment] 2016-12-05 18:05
Ok, i found it "sys_file". Now I have only to think about what I can do for individual pictures the cache can delete ....

**Comment by lochmueller** [comment] 2016-12-05 19:09
The problem is, that the cache do not store the original name of the image. One solution could be, to add the md5sum of the base name to the realurl image hash. I suggest to transfer the "custom cache" to a real caching framework cache. Like the StaticFIleCache: https://github.com/lochmueller/staticfilecache/tree/master/Classes/Cache There is also a file in the filesystem and a DB entry with technical information....

**Comment by fritzdacat** [comment] 2016-12-05 19:49
If I want to delete the entries myself, I would have to look for the right entries and delete them from "sys_file", "sys_file_metadata" and "sys_file_processedfile", or?

**Comment by lochmueller** [comment] 2016-12-05 20:24
No. Never deleted sys_file* ("sys_file", "sys_file_metadata" and "sys_file_processedfile") entries. All sys_file* entries are no caches!!! You can rebuild the file name alias: https://github.com/lochmueller/fl_realurl_image/blob/master/ext_tables.sql or drop cache information: https://github.com/lochmueller/fl_realurl_image/blob/master/ext_localconf.php#L8

**Comment by fritzdacat** [comment] 2016-12-05 21:43
I do not want to change the cache name of the image, I would like that if a picture is changed by an import (not over the Typo3 Backend) also the new picture is displayed ...

**Comment by lochmueller** [comment] 2016-12-05 21:50
OK... then i will close this issue. It is not related to the fl_realurl_image extension. You have to handle this requirement in the ResourceRepository and ResourceServices of the core... If you need a good entry point, I suggest to ask the question in the TYPO3 Slack again...

**Closed as completed by lochmueller** 2016-12-05 21:50 UTC
